version: '3'
services:
  postgresql:
    image: postgres:11.3
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - postgresql_data:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env.development
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    links:
      - postgresql
    depends_on:
      - postgresql
volumes:
  postgresql_data: 
  bundler_gems:
